### ISSUE TITLE
Exception when no previous migrations

### ISSUE THREAD

**Issue by LECbg** [BezBartek/django-db-views#7]
I just got an exception while running command `makeviewmigrations`. I could realise it was thrown because there were no previous migrations for that app (or at least I think so). This is the trace I got:

```
/app # python manage.py makeviewmigrations devices
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django_db_views/management/commands/makeviewmigrations.py", line 75, in handle
    migration_name=self.migration_name,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/autodetector.py", line 43, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/usr/local/lib/python3.7/site-packages/django_db_views/autodetector.py", line 66, in _detect_changes
    self.generate_views_operations(graph)
  File "/usr/local/lib/python3.7/site-packages/django_db_views/autodetector.py", line 103, in generate_views_operations
    graph, app_label, view_model._meta.db_table
  File "/usr/local/lib/python3.7/site-packages/django_db_views/autodetector.py", line 134, in get_previous_view_definition_state
    last_node = graph.leaf_nodes(app_label)[0]
IndexError: list index out of range
```

This may be the expected behaviour, though? If so, I think it isn't mentioned in the docs.

I can't assure this exception is due to a missing first migration because when I create it, I get the following exception and I can't figure out why:

```
/app # python manage.py makeviewmigrations devices
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django_db_views/management/commands/makeviewmigrations.py", line 75, in handle
    migration_name=self.migration_name,
  File "/usr/local/lib/python3.7/site-packages/django/db/migrations/autodetector.py", line 43, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/usr/local/lib/python3.7/site-packages/django_db_views/autodetector.py", line 66, in _detect_changes
    self.generate_views_operations(graph)
  File "/usr/local/lib/python3.7/site-packages/django_db_views/autodetector.py", line 118, in generate_views_operations
    BackwardViewMigration(current_view_definition.strip(";"), view_model._meta.db_table),
AttributeError: 'NoneType' object has no attribute 'strip'
```

I tried with both view_definition as string attribute and as static method. If you need more information, let me know.

Thank you for your work!

**Comment by LECbg** [comment]
I kept racking my brains about exception `AttributeError: 'NoneType' object has no attribute 'strip'`. I think commit https://github.com/BezBartek/django-db-views/commit/bac702200614a3687a2af8f7e71aac2f4753ce5a is the one introducing the bug, because as far as I can guess, `get_previous_view_definition_state` is expected to return `None` whenever no previous view migration is found, so `.strip(';')` can't be used on `current_view_definition`.

Hope this helps!

**Comment by LECbg** [comment]
Based on what I've just been researching... I think exception `IndexError: list index out of range` is due to `graph.leaf_nodes(app_label)` returning an empty array when there are no previous migrations.

**Comment by BezBartek** [comment]
Thank you!! I will test it and if everything is ok, then I will merge your pull request. I have a really busy weekend, I can't do it today, but I will try to do so as soon as I can.
